# „Erstellen Sie eine Docker-Compose-Datei mit zwei Services, die die Methode und die Tests ausführen.“

services:
  # Erster Container: Führt automatisch pytest aus
  pytest-runner:
    build: .                 # Benutze das Dockerfile im aktuellen Verzeichnis
    volumes:
      - .:/app               # Binde das aktuelle Projektverzeichnis in den Container ein
    working_dir: /app        # Setze das Arbeitsverzeichnis im Container auf /app
    command: pytest          # Führe im Container den Befehl 'pytest' aus

  # Zweiter Container: Führt ein Beispiel mit der Methode aus
  method-runner:
    build: .                 # Nutzt dasselbe Dockerfile
    volumes:
      - .:/app               # Projektordner wird wieder eingebunden
    working_dir: /app        # Arbeitsverzeichnis bleibt gleich
    command: python run_method.py  # Führt das Skript aus, das die Methode testet
